### ISSUE TITLE
Could not load type: Invalid Token After using this tool 

### ISSUE THREAD

**Issue by MQREFP** [SychicBoy/NETReactorSlayer#27] opened 2022-05-16 16:43 UTC
**Describe the bug**
After cleaning through Net Reactor Slayer When we Compose SMS in Software. AT every character we enter software gives error.

**Target obfuscated file**
https://workupload.com/file/Q2kgRpZY3Lv

**Screenshots**
https://ibb.co/FWXMTPk

**OS Version:**
Windows 11 64bit

**Comment by SychicBoy** [comment] 2022-05-16 16:51
You should use `preserve all metadata tokens` option.

**Comment by MQREFP** [comment] 2022-05-16 16:53
I used it but same result

**Comment by SychicBoy** [comment] 2022-05-16 16:55
So you should remove strong-name from assembly.

**Comment by MQREFP** [comment] 2022-05-16 17:00
Nope still same issue

**Comment by MQREFP** [comment] 2022-05-16 17:04
I use your tool net reactor slayer latest version but its not working.
But I also used de4dot by mobile46 it's tool working properly with extra argument --dont-rename

**Comment by MQREFP** [comment] 2022-05-16 17:06
Here is the link of tool which is working properly
https://github.com/mobile46/de4dot

**Comment by SychicBoy** [comment] 2022-05-16 17:12
You should remove strong-name from file that deobfuscated by .NETReactorSlayer using a third-party tool.

**Comment by MQREFP** [comment] 2022-05-16 17:21
But in release 4.0 you have written that you added strong name removal protection

**Comment by SychicBoy** [comment] 2022-05-16 17:24
`strong-name removal protection` is one of .NET Reactor protection features.
This feature prevent assembly strong-name gets removed by third-parties.

**Comment by MQREFP** [comment] 2022-05-16 17:24
Oh now I understand

**Comment by SychicBoy** [comment] 2022-05-16 17:25
Ok.

**Comment by SychicBoy** [comment] 2022-05-16 21:47
Duplicate of #26.

**Comment by SychicBoy** [comment] 2022-05-16 21:50
Duplicate of #26

**Comment by MQREFP** [comment] 2022-08-29 09:11
@SychicBoy any update?

**Closed** 2022-09-26 00:48 UTC
Labels: bug, duplicate
